In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
house = pd.read_csv("C:\\Users\\shama\\property_info1.csv")
house

,Location,Bedrooms,Bathrooms,Total_sqft,Price_per_sqft,Area_Type,Price(Lakhs)
0,2 BHK Apartment in Maruthi Nagar,2,2,959sq.ft.,4171,Built-upArea,42.00
1,3 BHK Apartment in 3rd Phase JP Nagar,3,3,"2,280sq.ft.",9868,Built-upArea,225.00
2,11 Bedroom House in 8th Phase JP Nagar,11,11,"1,200sq.ft.",15000,PlotArea,180.00
3,3 BHK Apartment in CV Raman Nagar,3,3,"2,189sq.ft.",10507,CarpetArea,230.00
4,2 BHK Apartment in CV Raman Nagar,2,2,"1,165sq.ft.",5579,CarpetArea,65.00
...,...,...,...,...,...,...,...
1637,3 BHK Apartment in Nehru Nagar,3,2,"1,275sq.ft.",5800,Superbuilt-up,73.95
1638,2 BHK Apartment in Sarjapur Road,2,2,"1,049sq.ft.",5243,CarpetArea,55.00
1639,2 BHK Apartment in Addischetan Layout,2,2,"1,000sq.ft.",5800,CarpetArea,58.00
1640,2 Bedroom House in Kengeri,2,1,650sq.ft.,8923,Built-upArea,58.00
1641,3 Bedroom House in Kaggadasapura,3,4,900sq.ft.,13888,Built-upArea,125.00

In [3]:
 house[['a','b','c']]=house.Location.str.split('in',expand=True)

In [4]:
house

,Location,Bedrooms,Bathrooms,Total_sqft,Price_per_sqft,Area_Type,Price(Lakhs),a,b,c
0,2 BHK Apartment in Maruthi Nagar,2,2,959sq.ft.,4171,Built-upArea,42.00,2 BHK Apartment,Maruthi Nagar,None
1,3 BHK Apartment in 3rd Phase JP Nagar,3,3,"2,280sq.ft.",9868,Built-upArea,225.00,3 BHK Apartment,3rd Phase JP Nagar,None
2,11 Bedroom House in 8th Phase JP Nagar,11,11,"1,200sq.ft.",15000,PlotArea,180.00,11 Bedroom House,8th Phase JP Nagar,None
3,3 BHK Apartment in CV Raman Nagar,3,3,"2,189sq.ft.",10507,CarpetArea,230.00,3 BHK Apartment,CV Raman Nagar,None
4,2 BHK Apartment in CV Raman Nagar,2,2,"1,165sq.ft.",5579,CarpetArea,65.00,2 BHK Apartment,CV Raman Nagar,None
...,...,...,...,...,...,...,...,...,...,...
1637,3 BHK Apartment in Nehru Nagar,3,2,"1,275sq.ft.",5800,Superbuilt-up,73.95,3 BHK Apartment,Nehru Nagar,None
1638,2 BHK Apartment in Sarjapur Road,2,2,"1,049sq.ft.",5243,CarpetArea,55.00,2 BHK Apartment,Sarjapur Road,None
1639,2 BHK Apartment in Addischetan Layout,2,2,"1,000sq.ft.",5800,CarpetArea,58.00,2 BHK Apartment,Addischetan Layout,None
1640,2 Bedroom House in Kengeri,2,1,650sq.ft.,8923,Built-upArea,58.00,2 Bedroom House,Kengeri,None
1641,3 Bedroom House in Kaggadasapura,3,4,900sq.ft.,13888,Built-upArea,125.00,3 Bedroom House,Kaggadasapura,None

In [5]:
house[['t','s']] = house.Total_sqft.str.split('sq.ft',expand=True)

In [6]:
house

,Location,Bedrooms,Bathrooms,Total_sqft,Price_per_sqft,Area_Type,Price(Lakhs),a,b,c,t,s
0,2 BHK Apartment in Maruthi Nagar,2,2,959sq.ft.,4171,Built-upArea,42.00,2 BHK Apartment,Maruthi Nagar,None,959,.
1,3 BHK Apartment in 3rd Phase JP Nagar,3,3,"2,280sq.ft.",9868,Built-upArea,225.00,3 BHK Apartment,3rd Phase JP Nagar,None,"2,280",.
2,11 Bedroom House in 8th Phase JP Nagar,11,11,"1,200sq.ft.",15000,PlotArea,180.00,11 Bedroom House,8th Phase JP Nagar,None,"1,200",.
3,3 BHK Apartment in CV Raman Nagar,3,3,"2,189sq.ft.",10507,CarpetArea,230.00,3 BHK Apartment,CV Raman Nagar,None,"2,189",.
4,2 BHK Apartment in CV Raman Nagar,2,2,"1,165sq.ft.",5579,CarpetArea,65.00,2 BHK Apartment,CV Raman Nagar,None,"1,165",.
...,...,...,...,...,...,...,...,...,...,...,...,...
1637,3 BHK Apartment in Nehru Nagar,3,2,"1,275sq.ft.",5800,Superbuilt-up,73.95,3 BHK Apartment,Nehru Nagar,None,"1,275",.
1638,2 BHK Apartment in Sarjapur Road,2,2,"1,049sq.ft.",5243,CarpetArea,55.00,2 BHK Apartment,Sarjapur Road,None,"1,049",.
1639,2 BHK Apartment in Addischetan Layout,2,2,"1,000sq.ft.",5800,CarpetArea,58.00,2 BHK Apartment,Addischetan Layout,None,"1,000",.
1640,2 Bedroom House in Kengeri,2,1,650sq.ft.,8923,Built-upArea,58.00,2 Bedroom House,Kengeri,None,650,.
1641,3 Bedroom House in Kaggadasapura,3,4,900sq.ft.,13888,Built-upArea,125.00,3 Bedroom House,Kaggadasapura,None,900,.

In [7]:
house=house.drop(['c','s','Location','Total_sqft'],axis=1)
house

,Bedrooms,Bathrooms,Price_per_sqft,Area_Type,Price(Lakhs),a,b,t
0,2,2,4171,Built-upArea,42.00,2 BHK Apartment,Maruthi Nagar,959
1,3,3,9868,Built-upArea,225.00,3 BHK Apartment,3rd Phase JP Nagar,"2,280"
2,11,11,15000,PlotArea,180.00,11 Bedroom House,8th Phase JP Nagar,"1,200"
3,3,3,10507,CarpetArea,230.00,3 BHK Apartment,CV Raman Nagar,"2,189"
4,2,2,5579,CarpetArea,65.00,2 BHK Apartment,CV Raman Nagar,"1,165"
...,...,...,...,...,...,...,...,...
1637,3,2,5800,Superbuilt-up,73.95,3 BHK Apartment,Nehru Nagar,"1,275"
1638,2,2,5243,CarpetArea,55.00,2 BHK Apartment,Sarjapur Road,"1,049"
1639,2,2,5800,CarpetArea,58.00,2 BHK Apartment,Addischetan Layout,"1,000"
1640,2,1,8923,Built-upArea,58.00,2 Bedroom House,Kengeri,650
1641,3,4,13888,Built-upArea,125.00,3 Bedroom House,Kaggadasapura,900

In [8]:
house.rename(columns = {'a':'Title','b':'Locations','t':'Total_sqft'},inplace=True)

In [9]:
house

,Bedrooms,Bathrooms,Price_per_sqft,Area_Type,Price(Lakhs),Title,Locations,Total_sqft
0,2,2,4171,Built-upArea,42.00,2 BHK Apartment,Maruthi Nagar,959
1,3,3,9868,Built-upArea,225.00,3 BHK Apartment,3rd Phase JP Nagar,"2,280"
2,11,11,15000,PlotArea,180.00,11 Bedroom House,8th Phase JP Nagar,"1,200"
3,3,3,10507,CarpetArea,230.00,3 BHK Apartment,CV Raman Nagar,"2,189"
4,2,2,5579,CarpetArea,65.00,2 BHK Apartment,CV Raman Nagar,"1,165"
...,...,...,...,...,...,...,...,...
1637,3,2,5800,Superbuilt-up,73.95,3 BHK Apartment,Nehru Nagar,"1,275"
1638,2,2,5243,CarpetArea,55.00,2 BHK Apartment,Sarjapur Road,"1,049"
1639,2,2,5800,CarpetArea,58.00,2 BHK Apartment,Addischetan Layout,"1,000"
1640,2,1,8923,Built-upArea,58.00,2 Bedroom House,Kengeri,650
1641,3,4,13888,Built-upArea,125.00,3 Bedroom House,Kaggadasapura,900

In [11]:
house1=house.loc[:,['Title','Locations','Bedrooms','Bathrooms','Total_sqft','Price_per_sqft','Price(Lakhs)','Area_Type']]

In [16]:
house1.rename(columns={'Title':'title', 'Locations':'location','Bedrooms':'bhk','Bathrooms':'bath','Total_sqft':'total_sqft','Price_per_sqft':'price_per_sqft','Price(Lakhs)':'price','Area_Type':'area_type'}, inplace=True)

In [16]:
house1.to_csv("Property_info1")